
export const AVAILABLE_STOCKS = [
  'SPY', 'SSO', 'UPRO', 'QQQ', 'QLD', 'TQQQ', 'SOXX', 'USD', 'SOXL', 'STRC', 'BIL', 'ICSH', 'SGOV'
];

// PRO/PREMIUM 전용 추가 종목
export const PAID_STOCKS = [
  'TSLA', 'TSLL', 'NVDA', 'NVDL', 'GOOGL', 'GGLL', 'PLTR', 'PTIR', 'COIN', 'CONL', 'MSTR', 'MSTX', 'BMNR'
];

// UI 리스트/필터링용 전체 종목
// 시세탭 종목 정보 순서를 제어하기 위해, 채권/현금성 ETF(BIL, ICSH, SGOV)를 가장 마지막으로 배치
export const ALL_STOCKS = [
  // 기본 인덱스/레버리지/기타
  'SPY', 'SSO', 'UPRO', 'QQQ', 'QLD', 'TQQQ', 'SOXX', 'USD', 'SOXL', 'STRC',
  // 유료 PRO/PREMIUM 전용 종목
  ...PAID_STOCKS,
  // 채권/현금성 ETF - 시세탭 종목 정보의 맨 마지막에 오도록
  'BIL', 'ICSH', 'SGOV',
];

export const STOCK_COLORS: Record<string, string> = {
  'SPY': '#4285F4', 'SSO': '#EA4335', 'UPRO': '#FBBC04', 'QQQ': '#34A853',
  'QLD': '#FF6D01', 'TQQQ': '#9C27B0', 'SOXX': '#00BCD4', 'USD': '#607D8B',
  'SOXL': '#E91E63', 'STRC': '#795548', 'BIL': '#3F51B5', 'ICSH': '#009688', 'SGOV': '#FF9800',
  // paid tickers (fallback 컬러)
  'TSLA': '#e11d48', 'TSLL': '#fb7185',
  'NVDA': '#22c55e', 'NVDL': '#4ade80',
  'GOOGL': '#3b82f6', 'GGLL': '#60a5fa',
  'PLTR': '#a855f7', 'PTIR': '#c084fc',
  'COIN': '#f59e0b', 'CONL': '#fbbf24',
  'MSTR': '#06b6d4', 'MSTX': '#22d3ee',
  'BMNR': '#64748b'
};

export const CUSTOM_GRADIENT_LOGOS: Record<string, { gradient: string; label: string }> = {
    'QQQ': { gradient: 'linear-gradient(135deg, #4285F4 0%, #9C27B0 100%)', label: 'NQ 100' },
    'QLD': { gradient: 'linear-gradient(135deg, #4285F4 0%, #9C27B0 100%)', label: '2X' },
    'TQQQ': { gradient: 'linear-gradient(135deg, #4285F4 0%, #9C27B0 100%)', label: '3X' },
    'USD': { gradient: 'linear-gradient(180deg, #87CEEB 0%, #32CD32 50%, #FFD700 100%)', label: '2x' },
    'SOXL': { gradient: 'linear-gradient(180deg, #9C27B0 0%, #E91E63 100%)', label: '3X' },
    'SOXX': { gradient: 'linear-gradient(180deg, #32CD32 0%, #00CED1 100%)', label: 'PHLX-SEMI' },
    'SSO': { gradient: 'linear-gradient(180deg, #1976D2 0%, #E53935 100%)', label: '2X' },
    'UPRO': { gradient: 'linear-gradient(180deg, #1976D2 0%, #E53935 100%)', label: '3X' },
    'SPY': { gradient: 'linear-gradient(180deg, #1976D2 0%, #E53935 100%)', label: 'S&P 500' },
    'STRC': { gradient: 'linear-gradient(180deg, #FF6B35 0%, #FFB347 100%)', label: 'MSTR-pref' },
    'ICSH': { gradient: 'linear-gradient(180deg, #0057B7 0%, #FFD700 100%)', label: 'SHORT TERM CORP' },
    'SGOV': { gradient: 'linear-gradient(180deg, #2E7D32 0%, #9CCC65 100%)', label: 'SHORT-TERM GOVT' },
    'BIL': { gradient: 'linear-gradient(180deg, #008B8B 0%, #D4AF37 100%)', label: 'SHORT-TERM TREAS' },

    // Paid tickers (간단한 그라데이션 배지, 실제 로고 도입 전까지)
    'TSLA': { gradient: 'linear-gradient(135deg, #ef4444 0%, #7f1d1d 100%)', label: 'TESLA' },
    'TSLL': { gradient: 'linear-gradient(135deg, #fb7185 0%, #be123c 100%)', label: '2X TSLA' },
    'NVDA': { gradient: 'linear-gradient(135deg, #22c55e 0%, #14532d 100%)', label: 'NVIDIA' },
    'NVDL': { gradient: 'linear-gradient(135deg, #4ade80 0%, #166534 100%)', label: '2X NVDA' },
    'GOOGL': { gradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)', label: 'ALPHABET' },
    'GGLL': { gradient: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)', label: '2X GOOG' },
    'PLTR': { gradient: 'linear-gradient(135deg, #a855f7 0%, #581c87 100%)', label: 'PALANTIR' },
    'PTIR': { gradient: 'linear-gradient(135deg, #c084fc 0%, #6d28d9 100%)', label: '2X PLTR' },
    'COIN': { gradient: 'linear-gradient(135deg, #f59e0b 0%, #92400e 100%)', label: 'COINBASE' },
    'CONL': { gradient: 'linear-gradient(135deg, #fbbf24 0%, #b45309 100%)', label: '2X COIN' },
    'MSTR': { gradient: 'linear-gradient(135deg, #06b6d4 0%, #164e63 100%)', label: 'MICROSTRAT' },
    'MSTX': { gradient: 'linear-gradient(135deg, #22d3ee 0%, #0e7490 100%)', label: '2X MSTR' },
    'BMNR': { gradient: 'linear-gradient(135deg, #64748b 0%, #0f172a 100%)', label: 'BMNR' }
};

export const MOCK_PRICES: Record<string, number> = {
  SGOV: 100.5, ICSH: 50.2, BIL: 95.8, STRC: 25.3, QQQ: 380.5,
  QLD: 45.2, TQQQ: 35.8, SOXX: 520.3, USD: 1.0, SOXL: 28.5,
  SPY: 450.2, SSO: 65.3, UPRO: 42.8
};

export const I18N = {
  ko: {
    dashboard: "대시보드",
    markets: "시세",
    history: "투자이력",
    membership: "멤버십",
    portfolioMgmt: "포트폴리오 관리",
    newPortfolio: "새 포트폴리오",
    totalValuation: "총 평가 금액",
    gain24h: "24H 변동",
    activeStrategy: "활성 전략",
    invested: "투자 금액",
    yield: "수익률",
    dailyExecution: "일별 매매 실행",
    terminate: "전략 종료하기",
    aiAdvisor: "AI 어드바이저",
    settlementHistory: "정산 히스토리",
    globalMarkets: "글로벌 마켓",
    searchTicker: "티커 검색...",
    launchStrategy: "전략 시작",
    systematicAccumulation: "일별 종가를 바탕으로 체계적인 중/장기 분할 매수 관리 시스템입니다.",
    pulseTitle: "시스템 상태",
    pulseStatus: "정상",
    quickInput: "빠른 매매 입력",
    tradeExecutionRecord: "상세 매매 실행 기록",
    buy: "매수",
    sell: "매도",
    save: "저장하기",
    cancel: "취소",
    executionPrice: "체결 단가",
    quantity: "수량",
    calculatedQty: "자동 계산 수량",
    calculatedFee: "매매 수수료",
    totalAmount: "최종 정산 금액",
    stock: "종목",
    date: "매수일",
    sellDate: "매도일",
    fee: "수수료",
    secFee: "유관 비용 (0.003%) (추정)",
    totalProfit: "누적 수익",
    successRate: "성공률",
    closedStrategies: "종료된 전략",
    noHistory: "기록된 내역이 없습니다.",
    viewSettlement: "정산 상세보기",
    login: "로그인",
    signup: "회원가입",
    logout: "로그아웃",
    changePassword: "비밀번호 변경",
    email: "이메일 주소",
    password: "비밀번호",
    activeSection: "현재 활성 구간",
    section: "구간",
    aiScan: "AI 매매 인식",
    aiScanSub: "스크린샷 자동 분석",
    dropImageOrClick: "여기에 이미지를 드롭하거나 클릭",
    pasteShortcut: "PASTE (CTRL+V)",
    pasteImageButton: "복사 이미지 붙여넣기",
    pasteImageUnsupported: "이 브라우저는 클립보드 이미지 붙여넣기를 지원하지 않습니다.",
    pasteImageNotFound: "클립보드에 이미지가 없습니다.",
    pasteImageError: "클립보드 이미지 읽기에 실패했습니다. 브라우저 권한을 확인하거나 Ctrl+V로 붙여넣기 해주세요.",
    screenshotOnly: "SCREENSHOT ONLY",
    aiScanStart: "AI 스캔 시작",
    aiScanHint: "증권사 앱의 체결 내역 화면을 캡쳐해서 올려주시면 자동으로 정보를 입력합니다.",
    aiScanError: "이미지를 인식할 수 없습니다. 다시 시도하거나 직접 입력해주세요.",
    aiScanRateLimit: "현재 요청이 많아 AI 서비스 이용이 지연되고 있습니다. 잠시 후 다시 시도해주세요.",
    aiConfirmSave: "확인 후 저장",
    aiRecognizedTrades: "인식된 매매 내역",
    sectionPartialProfit: "중간익절",
    sectionWatchRsiNotMet: "관망 (RSI 조건 미충족)",
    sectionWatchAlignmentNotMet: "관망 (정배열 미충족)",
    sectionWatchBothNotMet: "관망 (정배열 미충족, RSI 조건 미충족)",
    backtest: "백테스트",
    backtestSubtitle: "과거 2년 데이터를 통해 내 전략의 수익과 위험을 검증하세요.",
    backtestPeriod: "백테스트 기간",
    strategyMaTitle: "이평선 구간매수",
    strategyMaDesc: "이평선과 RSI를 결합한 고급 구간 대응 전략",
    strategyMultiSplitTitle: "다분할 매매법",
    strategyMultiSplitDesc: "목표 수익률 기반의 체계적 가변 분할 매수",
    strategyNoStopMultiSplitTitle: "다분할 매매법(무손절)",
    strategyNoStopMultiSplitDesc: "손절 없이 평단가 LOC와 고가 LOC로 나누어 기계적으로 매수하는 공격적 전략",
    backtestParamsTitle: "백테스트 파라미터 설정",
    backtestParamsSubtitle: "SIMULATION SETTINGS",
    backtestRun: "백테스트 실행",
    backtestMocNote: "일별 종가 매수 기준입니다.",
    rsiComingSoon: "업데이트 예정입니다.",
    rsiUse: "RSI 사용",
    alignmentUse: "정배열일 때만 매수 (MA a > MA b)",
    totalReturn: "누적 수익률",
    cagr: "연평균 성장률",
    mdd: "최대 낙폭",
    mddHint: "전략 유지 결정의 핵심",
    winRate: "승률",
    assetGrowthCurve: "자산 성장 곡선",
    benchmarkCompare: "벤치마크 비교 (PRO)",
    benchmarkCompareUpgrade: "UPGRADE TO COMPARE WITH S&P 500 & NASDAQ",
    upgradeNow: "UPGRADE NOW",
    drawdownChart: "낙폭 차트 (DRAWDOWN)",
    drawdownHint: "*과거 최대 하락 폭을 확인하여 리스크를 관리하세요.",
    sharpeRatio: "샤프 지수",
    avgHoldingPeriod: "평균 보유 기간",
    days: "일",
    months: "개월",
    newBacktestSettings: "새로운 백테스트 설정",
    dailyBuyAmount: "매일 매수 금액",
    feeRate: "매매 수수료",
    feeRateUnit: "%",
    baseStock: "기준주식",
    section1: "구간 1",
    section2: "구간 2",
    section3: "구간 3",
    maPeriod: "이동평균선",
    rsiThreshold: "RSI 기준",
    takeProfit: "중간이익실현",
    takeProfitPct: "이익실현 %",
    targetReturnRate: "목표수익률",
    totalSplitCount: "총 분할 횟수",
    oneTimeAmount: "1회 매수금액",
    firstRoundStartHint: "1회차 매수를 시작하세요",
    overLimit: "매매 내역을 확인하세요. 총투자금을 초과했습니다.",
    firstHalf: "전반전",
    secondHalf: "후반전",
    quarterStopLoss: "쿼터 손절",
    strategyPreparing: "전략 준비 중",
    quarterReturnTip: "쿼터손절 → 복귀 : LOC 매도 또는 지정가 매도가 체결될 때.",
    quarterEntryTip: "정규 → 쿼터손절 : T > a-1 이면 자동 진입.",
    checkingSection: "구간 확인 중…",
    locBuy1: "LOC 매수1",
    locBuy2: "LOC 매수2",
    lowLoc: "저가 LOC",
    highLoc: "고가 LOC",
    locSell: "LOC 매도",
    limitSell: "지정가 매도",
    mocSell: "MOC 매도",
    firstBuyAmount: "1회 매수금",
    noStopFirstBuyHint: "첫 매수는 장중 아무 때나, 자유롭게 매수해 주세요.",
    noStopSplitComplete: "분할 매수가 모두 완료되었습니다. 추가 매수 없이 보유(존버)와 익절만 수행합니다.",
    noStopTakeProfitTarget: "익절 목표",
    noStopGuaranteedDailyFill: "매일 체결 보장용",
    quarterHint: "MOC 매도 하여 쿼터 손절 모드 시작",
    sharesUnit: "주",
    noOrder: "오늘 주문 요약은 앱에서 확인해 주세요.",
  },
  en: {
    dashboard: "Dashboard",
    markets: "Markets",
    history: "History",
    membership: "Membership",
    portfolioMgmt: "Portfolio Management",
    newPortfolio: "New Portfolio",
    totalValuation: "TOTAL VALUATION",
    gain24h: "24H GAIN",
    activeStrategy: "ACTIVE STRATEGY",
    invested: "INVESTED",
    yield: "YIELD",
    dailyExecution: "DAILY EXECUTION",
    terminate: "TERMINATE STRATEGY",
    aiAdvisor: "AI ADVISOR",
    settlementHistory: "Settlement History",
    globalMarkets: "Markets",
    searchTicker: "Search ticker...",
    launchStrategy: "Launch Strategy",
    systematicAccumulation: "Systematic asset accumulation through quantitative dip-buying strategies.",
    pulseTitle: "System Pulse",
    pulseStatus: "Healthy",
    quickInput: "Quick Input",
    tradeExecutionRecord: "Trade Execution Record",
    buy: "Buy",
    sell: "Sell",
    save: "Save",
    cancel: "Cancel",
    executionPrice: "Execution Price",
    quantity: "Quantity",
    calculatedQty: "Calculated Quantity",
    calculatedFee: "Calculated Fee",
    totalAmount: "Total Amount",
    stock: "Ticker",
    date: "Buy Date",
    sellDate: "Sell Date",
    fee: "Fee",
    secFee: "SEC Fee (0.003%) (Est.)",
    totalProfit: "Total Profit",
    successRate: "Success Rate",
    closedStrategies: "Closed Strategies",
    noHistory: "No history found.",
    viewSettlement: "View Settlement",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    changePassword: "Change Password",
    email: "Email Address",
    password: "Password",
    activeSection: "Active Section",
    section: "Section",
    aiScan: "AI Trade Recognition",
    aiScanSub: "Screenshot auto-analysis",
    dropImageOrClick: "Drop image here or click",
    pasteShortcut: "PASTE (CTRL+V)",
    pasteImageButton: "Paste copied image",
    pasteImageUnsupported: "This browser does not support clipboard image paste.",
    pasteImageNotFound: "No image found in clipboard.",
    pasteImageError: "Failed to read image from clipboard. Check browser permissions or use Ctrl+V to paste.",
    screenshotOnly: "SCREENSHOT ONLY",
    aiScanStart: "Start AI Scan",
    aiScanHint: "Upload a screenshot of your broker's execution screen and we'll auto-fill the trade info.",
    aiScanError: "Could not recognize the image. Try again or enter manually.",
    aiScanRateLimit: "AI service is busy. Please try again later.",
    aiConfirmSave: "Confirm & Save",
    aiRecognizedTrades: "Recognized trades",
    sectionPartialProfit: "Partial profit",
    sectionWatchRsiNotMet: "Watch (RSI not met)",
    sectionWatchAlignmentNotMet: "Watch (alignment not met)",
    sectionWatchBothNotMet: "Watch (alignment not met, RSI not met)",
    backtest: "Backtest",
    backtestSubtitle: "Verify your strategy's profit and risk using the past 2 years of data.",
    backtestPeriod: "Backtest Period",
    strategyMaTitle: "Moving Average Interval",
    strategyMaDesc: "Advanced interval strategy combining MAs and RSI",
    strategyMultiSplitTitle: "Multi-Split Strategy",
    strategyMultiSplitDesc: "Systematic variable split buying based on target return",
    strategyNoStopMultiSplitTitle: "No-Stop Multi-Split",
    strategyNoStopMultiSplitDesc: "Aggressive split-buy strategy that keeps buying with avg-price and premium LOC orders without stop-loss",
    backtestParamsTitle: "Backtest Parameter Settings",
    backtestParamsSubtitle: "SIMULATION SETTINGS",
    backtestRun: "Run Backtest",
    backtestMocNote: "Based on daily closing price buy (MOC).",
    rsiComingSoon: "Coming soon.",
    rsiUse: "Enable RSI",
    alignmentUse: "Buy only when MA a > MA b",
    totalReturn: "Total Return",
    cagr: "CAGR",
    mdd: "Max Drawdown",
    mddHint: "Key to deciding whether to maintain the strategy",
    winRate: "Win Rate",
    assetGrowthCurve: "Asset Growth Curve",
    benchmarkCompare: "Benchmark Compare (PRO)",
    benchmarkCompareUpgrade: "UPGRADE TO COMPARE WITH S&P 500 & NASDAQ",
    upgradeNow: "UPGRADE NOW",
    drawdownChart: "Drawdown Chart",
    drawdownHint: "*Check past maximum drawdown to manage risk.",
    sharpeRatio: "Sharpe Ratio",
    avgHoldingPeriod: "Avg Holding Period",
    days: "days",
    months: "months",
    newBacktestSettings: "New Backtest Settings",
    dailyBuyAmount: "Daily Buy Amount",
    feeRate: "Fee Rate",
    feeRateUnit: "%",
    baseStock: "Base Stock",
    section1: "Section 1",
    section2: "Section 2",
    section3: "Section 3",
    maPeriod: "MA Period",
    rsiThreshold: "RSI Threshold",
    takeProfit: "Take Profit",
    takeProfitPct: "Take Profit %",
    targetReturnRate: "Target Return %",
    totalSplitCount: "Total Splits",
    oneTimeAmount: "1st Buy Amount",
    firstRoundStartHint: "Start your 1st round buy",
    overLimit: "Check your trades. Total invested has exceeded the limit.",
    firstHalf: "First Half",
    secondHalf: "Second Half",
    quarterStopLoss: "Quarter Stop-Loss",
    strategyPreparing: "Strategy preparing",
    quarterReturnTip: "Quarter Stop-Loss → Return: When LOC sell or limit sell is executed.",
    quarterEntryTip: "Normal → Quarter Stop-Loss: Auto when T > a-1.",
    checkingSection: "Checking section…",
    locBuy1: "LOC Buy 1",
    locBuy2: "LOC Buy 2",
    lowLoc: "Low LOC",
    highLoc: "High LOC",
    locSell: "LOC Sell",
    limitSell: "Limit Sell",
    mocSell: "MOC Sell",
    firstBuyAmount: "1st Buy Amount",
    noStopFirstBuyHint: "For your first buy, feel free to buy anytime during market hours.",
    noStopSplitComplete: "All split buys are complete. Hold and wait for take profit without additional buys.",
    noStopTakeProfitTarget: "Take-profit target",
    noStopGuaranteedDailyFill: "For guaranteed daily fill",
    quarterHint: "Execute MOC sell to start quarter stop-loss mode",
    sharesUnit: "shares",
    noOrder: "Please check today's orders in the app.",
  }
};
