export const BACKTEST_DEFAULTS = {
  COMMON: {
    MONTHS: 24,
    ONE_TIME_AMOUNT_USD: 1_000,
    FEE_RATE_PERCENT: 0.25,
    TARGET_RETURN_RATE_PERCENT: 10,
    TOTAL_SPLIT_COUNT: 40,
  },
  MA: {
    BASE_STOCK: 'QQQ',
    RSI_THRESHOLD: 30,
    SHORT_PERIOD_DAYS: 20,
    SHORT_PERIOD_STOCK: 'TQQQ',
    SHORT_PERIOD_TAKE_PROFIT_PERCENT: 10,
    LONG_PERIOD_DAYS: 60,
    LONG_PERIOD_STOCK: 'QLD',
    LONG_PERIOD_TAKE_PROFIT_PERCENT: 10,
    BELOW_MA_STOCK: 'QQQ',
    BELOW_MA_TAKE_PROFIT_PERCENT: 10,
    DAILY_BUY_AMOUNT_USD: 1_000,
  },
  MULTI_SPLIT: {
    STOCK: 'TQQQ',
  },
  NO_STOP_MULTI_SPLIT: {
    STOCK: 'TQQQ',
    LOW_LOC_BUDGET_RATIO_PERCENT: 50,
    HIGH_LOC_PREMIUM_PERCENT: 15,
    TAKE_PROFIT_PERCENT: 10,
  },
} as const;
